name: aisle_vision

services:
  aisle-vision-bff:
    build:
      context: ..
      dockerfile: Dockerfile
    image: aisle_vision_api:latest
    container_name: aisle_vision_api
    ports:
      - "3000:3000"
    volumes:
      - ../src:/app/src
      - /app/node_modules
    depends_on:
      - aisle-vision-db
    environment:
      DATABASE_URL: postgresql://aislevision:Dejavu1985@db:5432/avdb_dev
      NODE_ENV: "development"
    command: npm run start:dev

  aisle-vision-db:
    image: postgres:16
    container_name: aisle_vision_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: aislevision
      POSTGRES_PASSWORD: Dejavu1985
      POSTGRES_DB: avdb_dev
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
