services:
    api:
        build:
            context: ..
            dockerfile: Dockerfile
        container_name: aisle_vision_api
        ports:
            - "80:3000"
        depends_on:
            - db
        environment:
            NODE_ENV: production
            DATABASE_URL: postgresql://aislevision:Dejavu1985@5432/avdb_prod
        command: node dist/main

    db:
        image: postgres:16
        container_name: aisle_vision_db_prod
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: aislevision
            POSTGRES_PASSWORD: Dejavu1985
            POSTGRES_DB: avdb_prod
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
